### ISSUE TITLE
Channel Hoping

### ISSUE THREAD

**Issue by dwayneboothe** [kalanda/esp8266-sniffer#13]
The project only scans probes on channel 13 and doesn't seem to detect anything from other channels.  I've been able to get it to scan through the channels but it doesn't loop back to channel 1 and ends/keeps scanning channel 13.

#define CHANNEL_HOP_INTERVAL_MS   200
static os_timer_t channelHop_timer;

/**
 * Callback for channel hoping
 */
void channelHop()
{
  // hoping channels 1-14
  uint8 new_channel = wifi_get_channel() + 1;
  if (new_channel > 14)
    new_channel = 1;
  wifi_set_channel(new_channel);
}

**Comment by evil-tom** [comment]
Did you solve this?
I'm having the same issue. It will count up through the channels once then stay on 13.

**Comment by kalanda** [comment]
Seems like channel 14 is disabled in ESP8266's firmware and cannot be set. Maybe is because [channel 14 is only available in Japan](https://kernelmag.dailydot.com/features/report/8051/the-mystery-of-wifi-channel-14/).

This issue is resolved with the last commit https://github.com/kalanda/esp8266-sniffer/commit/85d946b8ed414706acd8c10cb04fe7feb61e4c73
