### ISSUE TITLE
Trying to write data to an SD Card

### ISSUE THREAD

**Issue by cowpi3** [kalanda/esp8266-sniffer#5]
Hi I'm trying to output the data from this to an SD Card and can write everything but the SSID to the file on the card.

Can you help me by explaining how I can get the SSID in to a variable or string etc. so that I can use myFile.print(ssid);  or something similar?

It doesn't have to be a variable, it can be anything as longs as I can use myFile.print to get it into the file on the SD Card.

Thanks :)

**Comment by kalanda** [comment]
[Here](https://github.com/kalanda/esp8266-sniffer/blob/3df0334b316d9b6e6e36d46792ed9e8a8a8ccc52/src/main.ino#L73-L75) the code calls a custom function `printDataSpan` to print the SSID to the serial port by using the data and the length of SSID in order to get each byte from the packet. 
 
```
uint8_t SSID_length = snifferPacket->data[25];
Serial.print(" SSID: ");
printDataSpan(26, SSID_length, snifferPacket->data);

...

static void printDataSpan(uint16_t start, uint16_t size, uint8_t* data) {
  for(uint16_t i = start; i < DATA_LENGTH && i < start+size; i++) {
    Serial.write(data[i]);
  }
}
```

You can create a similar function to print the SSID to the SDCard with something like this (not tested code):

```
static void printDataSpanToSdCard(uint16_t start, uint16_t size, uint8_t* data) {
  for(uint16_t i = start; i < DATA_LENGTH && i < start+size; i++) {
    myfile.print(data[i]);
  }
}
```

I hope it helps :)

**Comment by kalanda** [comment]
@cowpi3 maybe you have to remove the `static` word in the function definition to access to the global `myfile` (not sure)

**Comment by cowpi3** [comment]
@kalanda thank you for getting back to me, I'll have a go at this later and let you know how I get on!

Thanks again

**Comment by cowpi3** [comment]
@kalanda thanks again for your help I've put:

`void printDataSpanToSdCard(uint16_t start, uint16_t size, uint8_t* data) {
  for(uint16_t i = start; i < DATA_LENGTH && i < start+size; i++) {
    dataFile.print(data[i]);
  }
}`

below the printDataSpan and then put:

`  dataFile.print(" SSID: ");
  printDataSpanToSdCard(26, SSID_length, snifferPacket->data);`

after the serial.print(" SSID: "); Whilst I am getting the SSIDs in the serial monitor they are being writted to the SD Card in DEC.

I'm really not sure why?

Thanks

**Comment by kalanda** [comment]
@cowpi3 try with `dataFile.write(data[i]);` instead of `dataFile.print(data[i]);`

**Comment by DarrenRainey** [comment]
Can someone please help me to get this data logging to work on the nodemcu using the arduino IDE currently when I try to use an SD card it gives me an initialisation error after a bit of research I found that this was because the nodemcu has the FatFs function disabled by default and currently I cannot find a way to both write the firmware with the FatFs enabled and this code.

**Comment by kalanda** [comment]
Sorry @DarrenRainey but I can't help you with that issue since I didn't log to a SD card before. I hope you find the solution somewhere :)
